"""add temporal validity to memories

Revision ID: 6963e7e93be8
Revises: dba9451311a0
Create Date: 2026-10-05 04:00:48.233272

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6963e7e93be8'
down_revision: str | Sequence[str] | None = 'dba9451311a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memories', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'valid_to')
    op.drop_column('memories', 'valid_from')
    # ### end Alembic commands ###
